- product: RPH1
  versions:
  - version: V4
    type: pcb
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/main/Pictures/view1.jpg
    description: This is a 3-in-1 UART to RS485 converter. Can be used as a Raspberry Pi Hat, can connect to Arduino, and can connect to a computer via USB. It contains a CP2102N chip.
    schematic: https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/main/PCB/V4/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial:
    github: https://github.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/V4
  - version: V9
    type: pcb
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: 
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153158.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153203.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter_kit/RS485_adapter_kit_20250714153104.jpg
    description: This is a 3-in-1 UART to RS485 converter. Can be used as a Raspberry Pi Hat, can connect to Arduino, and can connect to a computer via USB. It contains a CP2102N chip.
    schematic: https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/V9/PCB/schematic/V9-index-schTop.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial:
    github: https://github.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/V9
- product: RS1
  versions:
  - version: '1.1'
    type: pcb
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: 
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153158.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153203.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter_kit/RS485_adapter_kit_20250714153104.jpg
    description: This is a 3-in-1 UART to RS485 converter. Can be used as a Raspberry Pi Hat, can connect to Arduino, and can connect to a computer via USB. It contains a CP2102N chip.
    schematic: https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/1.1/schematic/1.1-index-schTop.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial:
    github: https://github.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/1.1
  - version: '1.2'
    type: pcb
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: 
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153158.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter/RS485_adapter_20250714153203.jpg
    - https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/refs/heads/main/Pictures/adapter_kit/RS485_adapter_kit_20250714153104.jpg
    description: This is a 3-in-1 UART to RS485 converter. Can be used as a Raspberry Pi Hat, can connect to Arduino, and can connect to a computer via USB. It contains a CP2102N chip.
    schematic: https://raw.githubusercontent.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/1.2/PCB/schematic/1.2-index-schTop.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial:
    github: https://github.com/tomrodinger/Raspberry_Pi_HAT_RS485/tree/main/PCB/1.2
